
Maci\TranslatorBundle\Entity\Language:
    type: entity
    table: maci_translator_language
    repositoryClass: Maci\TranslatorBundle\Repository\LanguageRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            length: 63
        text:
            type: text
            nullable: true
        locale:
            type: string
            length: 10
