
services:

    maci.translator:
        class: Maci\TranslatorBundle\Controller\TranslatorController
        arguments: ["@doctrine.orm.entity_manager","@security.context","%locales%"]

    maci_translator.twig_extension:
        class: Maci\TranslatorBundle\Twig\TranslatorExtension
        arguments: ["@maci.translator"]
        tags:
            - { name: twig.extension }

    maci_translatorid.twig_extension:
        class: Maci\TranslatorBundle\Twig\TranslatorIdExtension
        arguments: ["@maci.translator"]
        tags:
            - { name: twig.extension }

    maci_translator.form.type.language:
        class: Maci\TranslatorBundle\Form\Type\LanguageType
        tags:
            - { name: form.type, alias: language }
