
services:

    Maci\TranslatorBundle\Controller\TranslatorController:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","%locales%"]

    maci.translator:
        alias: Maci\TranslatorBundle\Controller\TranslatorController
        public: true

    # Twig
    
    maci_translator.twig_extension:
        class: Maci\TranslatorBundle\Twig\TranslatorExtension
        arguments: ["@maci.translator"]
        tags:
            - { name: twig.extension }
