
services:

    maci_translator.twig_extension:
        class: Maci\TranslatorBundle\Twig\TranslatorExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }

    maci_translatorid.twig_extension:
        class: Maci\TranslatorBundle\Twig\TranslatorIdExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }

    maci_translator.form.type.language:
        class: Maci\TranslatorBundle\Form\Type\LanguageType
        tags:
            - { name: form.type, alias: language }
