
services:

    Maci\TranslatorBundle\Controller\TranslatorController:
        arguments: ["@doctrine.orm.entity_manager","@request_stack","%locales%"]

    maci.translator:
        alias: Maci\TranslatorBundle\Controller\TranslatorController
        public: true
    
    maci_translator.twig_extension:
        class: Maci\TranslatorBundle\Twig\TranslatorExtension
        arguments: ["@maci.translator"]
        tags:
            - { name: twig.extension }

    maci_translator_id.twig_extension:
        class: Maci\TranslatorBundle\Twig\TranslatorIdExtension
        arguments: ["@maci.translator"]
        tags:
            - { name: twig.extension }

    maci_translator_label.twig_extension:
        class: Maci\TranslatorBundle\Twig\TranslatorLabelExtension
        arguments: ["@maci.translator"]
        tags:
            - { name: twig.extension }

    maci_translator.form.type.language:
        class: Maci\TranslatorBundle\Form\Type\LanguageType
        tags:
            - { name: form.type, alias: language }
